[google_oauth]
client_id = "536936801426-bq8u0r27na73gv23nu88jrda15537qk4.apps.googleusercontent.com"
client_secret = "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pip install google-auth-oauthlib google-api-python-client google-auth-httplib2"